[package]
edition = "2021"
name    = "domparser"
version = "0.0.0"

[dependencies]
html5ever = { workspace = true }
indexmap  = { workspace = true }
markup5ever = "0.11.0"
tendril = "0.4.3"
markup5ever_rcdom = "0.3.0"
